### ISSUE TITLE
prevent replay of 'old' mappings with a lower sequenceNumber

### ISSUE THREAD

**Issue by swagendorp** [input-output-hk/offchain-metadata-tools#8]
It appears that validation still passes when updating an entry with a lower sequenceNumber

https://github.com/input-output-hk/metadata-registry-testnet/pull/59/files

**Comment by gitmachtl** [comment]
Short question about sequenceNumbers. Is it ok to swap out the json file with a totally fresh one from scratch? Or is it required to increment the sequenceNumbers at all costs to update an entry? If you don't have the submitted json file anymore, there is currently no parameter for the token-metadata-creator to set it to a specified sequenceNumber. So should we modify/increment the sequenceNumber after the json creation?

**Comment by sevanspowell** [comment]
@swagendorp The check on that PR was run before the script had been updated. It has since been fixed.

I recreated the circumstance of your PR to demonstrate: https://github.com/input-output-hk/metadata-registry-testnet/pull/92

Compare the output of the [original run](https://github.com/input-output-hk/metadata-registry-testnet/runs/2012477930?check_suite_focus=true) with [the new run](https://github.com/input-output-hk/metadata-registry-testnet/runs/2348605270). Notice the new run has two checkout steps, and the original run only has one. The new validation script does two checkouts so it can compare the two and see if sequence numbers have increased or decreased.
